[2025-08-04T21:07:43.727+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-04T21:07:43.758+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.train_model manual__2025-08-04T21:06:18.145419+00:00 [queued]>
[2025-08-04T21:07:43.774+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.train_model manual__2025-08-04T21:06:18.145419+00:00 [queued]>
[2025-08-04T21:07:43.775+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-08-04T21:07:43.795+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): train_model> on 2025-08-04 21:06:18.145419+00:00
[2025-08-04T21:07:43.803+0000] {standard_task_runner.py:72} INFO - Started process 111 to run task
[2025-08-04T21:07:43.807+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'turnstile_ml_pipeline', 'train_model', 'manual__2025-08-04T21:06:18.145419+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/turnstile_ml_pipeline.py', '--cfg-path', '/tmp/tmpc32vfm4b']
[2025-08-04T21:07:43.810+0000] {standard_task_runner.py:105} INFO - Job 92: Subtask train_model
[2025-08-04T21:07:43.833+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-04T21:07:43.881+0000] {task_command.py:467} INFO - Running <TaskInstance: turnstile_ml_pipeline.train_model manual__2025-08-04T21:06:18.145419+00:00 [running]> on host c3acc3669c6c
[2025-08-04T21:07:44.013+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='turnstile_ml_pipeline' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-08-04T21:06:18.145419+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-04T21:06:18.145419+00:00'
[2025-08-04T21:07:44.014+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-08-04T21:07:44.036+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-08-04T21:07:44.038+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n            python /opt/***/pipeline/train_register.py                             --user ***                 --password ***                 --host postgres                 --port 5432                 --db_name ny_sub_turnstiles                 --features_table turnstile_features         ']
[2025-08-04T21:07:44.049+0000] {subprocess.py:99} INFO - Output:
[2025-08-04T21:07:50.884+0000] {subprocess.py:106} INFO - 2025/08/04 21:07:50 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
[2025-08-04T21:07:50.886+0000] {subprocess.py:106} INFO - The git executable must be specified in one of the following ways:
[2025-08-04T21:07:50.887+0000] {subprocess.py:106} INFO -     - be included in your $PATH
[2025-08-04T21:07:50.888+0000] {subprocess.py:106} INFO -     - be set via $GIT_PYTHON_GIT_EXECUTABLE
[2025-08-04T21:07:50.889+0000] {subprocess.py:106} INFO -     - explicitly set via git.refresh(<full-path-to-git-executable>)
[2025-08-04T21:07:50.890+0000] {subprocess.py:106} INFO - 
[2025-08-04T21:07:50.891+0000] {subprocess.py:106} INFO - All git commands will error until this is rectified.
[2025-08-04T21:07:50.892+0000] {subprocess.py:106} INFO - 
[2025-08-04T21:07:50.893+0000] {subprocess.py:106} INFO - This initial message can be silenced or aggravated in the future by setting the
[2025-08-04T21:07:50.894+0000] {subprocess.py:106} INFO - $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
[2025-08-04T21:07:50.895+0000] {subprocess.py:106} INFO -     - quiet|q|silence|s|silent|none|n|0: for no message or exception
[2025-08-04T21:07:50.897+0000] {subprocess.py:106} INFO -     - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
[2025-08-04T21:07:50.898+0000] {subprocess.py:106} INFO -     - error|e|exception|raise|r|2: for a raised exception
[2025-08-04T21:07:50.899+0000] {subprocess.py:106} INFO - 
[2025-08-04T21:07:50.900+0000] {subprocess.py:106} INFO - Example:
[2025-08-04T21:07:50.901+0000] {subprocess.py:106} INFO -     export GIT_PYTHON_REFRESH=quiet
[2025-08-04T21:07:50.902+0000] {subprocess.py:106} INFO - 
[2025-08-04T21:07:51.319+0000] {subprocess.py:106} INFO - üèÉ View run fortunate-dove-65 at: http://mlflow:5000/#/experiments/2/runs/a59878d446c640a2b6572107f10205fa
[2025-08-04T21:07:51.321+0000] {subprocess.py:106} INFO - üß™ View experiment at: http://mlflow:5000/#/experiments/2
[2025-08-04T21:07:51.903+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-08-04T21:07:51.970+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-08-04T21:07:51.972+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=turnstile_ml_pipeline, task_id=train_model, run_id=manual__2025-08-04T21:06:18.145419+00:00, execution_date=20250804T210618, start_date=20250804T210743, end_date=20250804T210751
[2025-08-04T21:07:52.046+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-08-04T21:07:52.115+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-04T21:07:52.122+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
