[2025-07-13T19:38:15.326+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-13T19:38:15.364+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.train_model manual__2025-07-13T17:16:28+00:00 [queued]>
[2025-07-13T19:38:15.383+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.train_model manual__2025-07-13T17:16:28+00:00 [queued]>
[2025-07-13T19:38:15.384+0000] {taskinstance.py:2867} INFO - Starting attempt 6 of 6
[2025-07-13T19:38:15.408+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): train_model> on 2025-07-13 17:16:28+00:00
[2025-07-13T19:38:15.420+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=584) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-13T19:38:15.423+0000] {standard_task_runner.py:72} INFO - Started process 592 to run task
[2025-07-13T19:38:15.422+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'turnstile_ml_pipeline', 'train_model', 'manual__2025-07-13T17:16:28+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmpr2ljanxu']
[2025-07-13T19:38:15.426+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask train_model
[2025-07-13T19:38:15.456+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-13T19:38:15.523+0000] {task_command.py:467} INFO - Running <TaskInstance: turnstile_ml_pipeline.train_model manual__2025-07-13T17:16:28+00:00 [running]> on host d84888688479
[2025-07-13T19:38:15.660+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='turnstile_ml_pipeline' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-07-13T17:16:28+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-13T17:16:28+00:00'
[2025-07-13T19:38:15.662+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-13T19:38:15.697+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-07-13T19:38:15.699+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n            python /opt/***/pipeline/train_register.py                             --user ***                 --password ***                 --host postgres                 --port 5432                 --db_name ny_sub_turnstiles                 --features_table turnstile_features         ']
[2025-07-13T19:38:15.717+0000] {subprocess.py:99} INFO - Output:
[2025-07-13T19:38:21.071+0000] {subprocess.py:106} INFO - Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]
[2025-07-13T19:38:21.134+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-07-13T19:38:21.135+0000] {subprocess.py:106} INFO -   File "/opt/***/pipeline/train_register.py", line 29, in <module>
[2025-07-13T19:38:21.140+0000] {subprocess.py:106} INFO -     params_path = download_artifacts(
[2025-07-13T19:38:21.141+0000] {subprocess.py:106} INFO -                   ^^^^^^^^^^^^^^^^^^^
[2025-07-13T19:38:21.142+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/mlflow/artifacts/__init__.py", line 86, in download_artifacts
[2025-07-13T19:38:21.144+0000] {subprocess.py:106} INFO -     return _download_artifact_from_uri(
[2025-07-13T19:38:21.145+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T19:38:21.146+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/mlflow/tracking/artifact_utils.py", line 117, in _download_artifact_from_uri
[2025-07-13T19:38:21.147+0000] {subprocess.py:106} INFO -     return repo.download_artifacts(artifact_path=artifact_path, dst_path=output_path)
[2025-07-13T19:38:21.148+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T19:38:21.149+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/mlflow/store/artifact/runs_artifact_repo.py", line 210, in download_artifacts
[2025-07-13T19:38:21.150+0000] {subprocess.py:106} INFO -     model_out_path = self._download_model_artifacts(artifact_path, dst_path=dst_path)
[2025-07-13T19:38:21.151+0000] {subprocess.py:106} INFO -                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T19:38:21.152+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/mlflow/store/artifact/runs_artifact_repo.py", line 231, in _download_model_artifacts
[2025-07-13T19:38:21.153+0000] {subprocess.py:106} INFO -     if repo := self._get_logged_model_artifact_repo(run_id=run_id, name=model_name):
[2025-07-13T19:38:21.154+0000] {subprocess.py:106} INFO -                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T19:38:21.156+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/mlflow/store/artifact/runs_artifact_repo.py", line 154, in _get_logged_model_artifact_repo
[2025-07-13T19:38:21.158+0000] {subprocess.py:106} INFO -     if matched := next((m for m in iter_models() if m.source_run_id == run_id), None):
[2025-07-13T19:38:21.159+0000] {subprocess.py:106} INFO -                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T19:38:21.160+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/mlflow/store/artifact/runs_artifact_repo.py", line 154, in <genexpr>
[2025-07-13T19:38:21.161+0000] {subprocess.py:106} INFO -     if matched := next((m for m in iter_models() if m.source_run_id == run_id), None):
[2025-07-13T19:38:21.162+0000] {subprocess.py:106} INFO -                                    ^^^^^^^^^^^^^
[2025-07-13T19:38:21.163+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/mlflow/store/artifact/runs_artifact_repo.py", line 143, in iter_models
[2025-07-13T19:38:21.164+0000] {subprocess.py:106} INFO -     page = client.search_logged_models(
[2025-07-13T19:38:21.165+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T19:38:21.167+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/mlflow/tracking/client.py", line 5584, in search_logged_models
[2025-07-13T19:38:21.168+0000] {subprocess.py:106} INFO -     return self._tracking_client.search_logged_models(
[2025-07-13T19:38:21.169+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T19:38:21.170+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/mlflow/tracking/_tracking_service/client.py", line 881, in search_logged_models
[2025-07-13T19:38:21.171+0000] {subprocess.py:106} INFO -     return self.store.search_logged_models(
[2025-07-13T19:38:21.173+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T19:38:21.174+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/mlflow/store/tracking/rest_store.py", line 1057, in search_logged_models
[2025-07-13T19:38:21.175+0000] {subprocess.py:106} INFO -     response_proto = self._call_endpoint(SearchLoggedModels, req_body)
[2025-07-13T19:38:21.176+0000] {subprocess.py:106} INFO -                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T19:38:21.177+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/mlflow/store/tracking/rest_store.py", line 135, in _call_endpoint
[2025-07-13T19:38:21.178+0000] {subprocess.py:106} INFO -     return call_endpoint(
[2025-07-13T19:38:21.179+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^
[2025-07-13T19:38:21.180+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/mlflow/utils/rest_utils.py", line 590, in call_endpoint
[2025-07-13T19:38:21.181+0000] {subprocess.py:106} INFO -     response = verify_rest_response(response, endpoint)
[2025-07-13T19:38:21.182+0000] {subprocess.py:106} INFO -                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-13T19:38:21.183+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/mlflow/utils/rest_utils.py", line 310, in verify_rest_response
[2025-07-13T19:38:21.184+0000] {subprocess.py:106} INFO -     raise MlflowException(
[2025-07-13T19:38:21.184+0000] {subprocess.py:106} INFO - mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/logged-models/search failed with error code 404 != 200. Response body: '<!doctype html>
[2025-07-13T19:38:21.185+0000] {subprocess.py:106} INFO - <html lang=en>
[2025-07-13T19:38:21.186+0000] {subprocess.py:106} INFO - <title>404 Not Found</title>
[2025-07-13T19:38:21.187+0000] {subprocess.py:106} INFO - <h1>Not Found</h1>
[2025-07-13T19:38:21.188+0000] {subprocess.py:106} INFO - <p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>
[2025-07-13T19:38:21.189+0000] {subprocess.py:106} INFO - '
[2025-07-13T19:38:21.548+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-07-13T19:38:21.562+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-13T19:38:21.570+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=turnstile_ml_pipeline, task_id=train_model, run_id=manual__2025-07-13T17:16:28+00:00, execution_date=20250713T171628, start_date=20250713T193815, end_date=20250713T193821
[2025-07-13T19:38:21.614+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-13T19:38:21.615+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 14 for task train_model (Bash command failed. The command returned a non-zero exit code 1.; 592)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-13T19:38:21.668+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-07-13T19:38:21.698+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-13T19:38:21.706+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
